2022-03-17 17:10:28,794 INFO    MainThread:163767 [wandb_setup.py:_flush():75] Loading settings from /home/kg23/.config/wandb/settings
2022-03-17 17:10:28,794 INFO    MainThread:163767 [wandb_setup.py:_flush():75] Loading settings from /home/kg23/reading-group/CV/wandb/settings
2022-03-17 17:10:28,794 INFO    MainThread:163767 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-17 17:10:28,794 INFO    MainThread:163767 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'CV/models.py', 'program': '/home/kg23/reading-group/CV/models.py'}
2022-03-17 17:10:28,794 INFO    MainThread:163767 [wandb_init.py:_log_setup():405] Logging user logs to /home/kg23/reading-group/CV/wandb/run-20220317_171028-2goqopb8/logs/debug.log
2022-03-17 17:10:28,794 INFO    MainThread:163767 [wandb_init.py:_log_setup():406] Logging internal logs to /home/kg23/reading-group/CV/wandb/run-20220317_171028-2goqopb8/logs/debug-internal.log
2022-03-17 17:10:28,795 INFO    MainThread:163767 [wandb_init.py:init():439] calling init triggers
2022-03-17 17:10:28,795 INFO    MainThread:163767 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {'lr': 1, 'width': 100, 'depth': 3, 'steps': 1000, 'dataset_size': 10000}
2022-03-17 17:10:28,795 INFO    MainThread:163767 [wandb_init.py:init():492] starting backend
2022-03-17 17:10:28,795 INFO    MainThread:163767 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-17 17:10:28,806 INFO    MainThread:163767 [backend.py:ensure_launched():219] starting backend process...
2022-03-17 17:10:28,813 INFO    MainThread:163767 [backend.py:ensure_launched():224] started backend process with pid: 164079
2022-03-17 17:10:28,827 INFO    MainThread:163767 [wandb_init.py:init():501] backend started and connected
2022-03-17 17:10:28,834 INFO    MainThread:163767 [wandb_init.py:init():565] updated telemetry
2022-03-17 17:10:28,854 INFO    MainThread:163767 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-17 17:10:29,510 INFO    MainThread:163767 [wandb_run.py:_on_init():1759] communicating current version
2022-03-17 17:10:29,563 INFO    MainThread:163767 [wandb_run.py:_on_init():1763] got version response 
2022-03-17 17:10:29,564 INFO    MainThread:163767 [wandb_init.py:init():625] starting run threads in backend
2022-03-17 17:10:31,146 WARNING MainThread:163767 [wandb_init.py:init():975] interrupted
Traceback (most recent call last):
  File "/home/kg23/anaconda3/envs/rg/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 954, in init
    run = wi.init()
  File "/home/kg23/anaconda3/envs/rg/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 636, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/home/kg23/anaconda3/envs/rg/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 221, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "/home/kg23/anaconda3/envs/rg/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 432, in _communicate_run_start
    result = self._communicate(rec)
  File "/home/kg23/anaconda3/envs/rg/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 222, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/kg23/anaconda3/envs/rg/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/kg23/anaconda3/envs/rg/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/home/kg23/anaconda3/envs/rg/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
